ruby_luongvanchuong/Project_Ruby/config/routes.rb
Rails.application.routes.draw do
  resources :books
  resources :friends
  get 'about', to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

ruby_luongvanchuong/Project_Ruby/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

ruby_luongvanchuong/Project_Ruby/app/models/book.rb
class Book < ApplicationRecord
end

ruby_luongvanchuong/Project_Ruby/app/models/friend.rb
class Friend < ApplicationRecord
end

ruby_luongvanchuong/Project_Ruby/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ruby_luongvanchuong/Project_Ruby/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:masv_205, :hoten, :lop, :mansanh, :tensach, :tentacgia, :soBM, :ngaymuon, :ngaytra, :ghichu)
    end
end

ruby_luongvanchuong/Project_Ruby/app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :phone, :twiter)
    end
end

ruby_luongvanchuong/Project_Ruby/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

ruby_luongvanchuong/Project_Ruby/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby_luongvanchuong/Project_Ruby/app/helpers/books_helper.rb
module BooksHelper
end

ruby_luongvanchuong/Project_Ruby/app/helpers/friends_helper.rb
module FriendsHelper
end

ruby_luongvanchuong/Project_Ruby/app/helpers/pages_helper.rb
module PagesHelper
end

ruby_luongvanchuong/Project_Ruby/app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Masv_115:</strong>
    <%= book.masv_205 %>
  </p>

  <p>
    <strong>Hoten_115:</strong>
    <%= book.hoten %>
  </p>

  <p>
    <strong>Lop_115:</strong>
    <%= book.lop %>
  </p>

  <p>
    <strong>Mansanh_115:</strong>
    <%= book.mansanh %>
  </p>

  <p>
    <strong>Tensach_115:</strong>
    <%= book.tensach %>
  </p>

  <p>
    <strong>Tentacgia_115:</strong>
    <%= book.tentacgia %>
  </p>

  <p>
    <strong>Sobm_115:</strong>
    <%= book.soBM %>
  </p>

  <p>
    <strong>Ngaymuon_115:</strong>
    <%= book.ngaymuon %>
  </p>

  <p>
    <strong>Ngaytra_115:</strong>
    <%= book.ngaytra %>
  </p>

  <p>
    <strong>Ghichu:</strong>
    <%= book.ghichu %>
  </p>

</div>

ruby_luongvanchuong/Project_Ruby/app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :masv_205, style: "display: block" %>
    <%= form.text_field :masv_205 %>
  </div>

  <div>
    <%= form.label :hoten, style: "display: block" %>
    <%= form.text_field :hoten %>
  </div>

  <div>
    <%= form.label :lop, style: "display: block" %>
    <%= form.text_field :lop %>
  </div>

  <div>
    <%= form.label :mansanh, style: "display: block" %>
    <%= form.text_field :mansanh %>
  </div>

  <div>
    <%= form.label :tensach, style: "display: block" %>
    <%= form.text_field :tensach %>
  </div>

  <div>
    <%= form.label :tentacgia, style: "display: block" %>
    <%= form.text_field :tentacgia %>
  </div>

  <div>
    <%= form.label :soBM, style: "display: block" %>
    <%= form.text_field :soBM %>
  </div>

  <div>
    <%= form.label :ngaymuon, style: "display: block" %>
    <%= form.date_field :ngaymuon %>
  </div>

  <div>
    <%= form.label :ngaytra, style: "display: block" %>
    <%= form.date_field :ngaytra %>
  </div>

  <div>
    <%= form.label :ghichu, style: "display: block" %>
    <%= form.text_area :ghichu %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

ruby_luongvanchuong/Project_Ruby/app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

ruby_luongvanchuong/Project_Ruby/app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Books</h1>

<div id="books">
  <% @books.each do |book| %>
    <%= render book %>
    <p>
      <%= link_to "Show this book", book %>
    </p>
  <% end %>
</div>

<%= link_to "New book", new_book_path %>

ruby_luongvanchuong/Project_Ruby/app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

ruby_luongvanchuong/Project_Ruby/app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Back to books", books_path %>

  <%= button_to "Destroy this book", @book, method: :delete %>
</div>

ruby_luongvanchuong/Project_Ruby/app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :twiter, style: "display: block" %>
    <%= form.text_field :twiter %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

ruby_luongvanchuong/Project_Ruby/app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twiter: @</strong>
    <%= friend.twiter %>
  </p>
</div>

ruby_luongvanchuong/Project_Ruby/app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show", @friend %> |
  <%= link_to "Back", friends_path %>
</div>

ruby_luongvanchuong/Project_Ruby/app/views/friends/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Friends</h1>
<%= link_to "New friend", new_friend_path %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th scope="col">Phone</th>
      <th scope="col">twiter</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <th scope="row">1</th>
        <td><%= friend.first_name %></td>
        <td><%= friend.last_name %></td>
        <td><%= friend.phone %></td>
        <td>@<%= friend.twiter %></td>
        <td><%= link_to "Show", friend %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

ruby_luongvanchuong/Project_Ruby/app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path %>
</div>

ruby_luongvanchuong/Project_Ruby/app/views/friends/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @friend %>

<div>
  <%= link_to "Edit", edit_friend_path(@friend) %> |
  <%= link_to "Back", friends_path %>
  <%= button_to "Destroy", @friend, method: :delete %>
</div>

ruby_luongvanchuong/Project_Ruby/app/views/layouts/_footer.html.erb
<footer class="bg-light text-dark">
      <div class="container" >
            <div class="row">
                  <div class="col">
                        <h3>MDN</h3>
                        <ul>
                              <li>About</li>
                              <li>Hacks Blog</li>
                              <li>Careers</li>
                        </ul>
                  </div>
                  <div class="col">
                        <h3>Support</h3>
                        <ul>
                              <li>About</li>
                              <li>Hacks Blog</li>
                              <li>Careers</li>
                        </ul>
                  </div>
                  <div class="col">
                        <h3>Our communities</h3>
                        <ul>
                              <li>About</li>
                              <li>Hacks Blog</li>
                              <li>Careers</li>
                        </ul>
                  </div>
                  <div class="col">
                        <h3>Developers</h3>
                        <ul>
                              <li>About</li>
                              <li>Hacks Blog</li>
                              <li>Careers</li>
                        </ul>
                  </div>
            </div>
      </div>
</footer>

ruby_luongvanchuong/Project_Ruby/app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "My Blog", root_path, class:'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:'nav-link active' %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Friends", friends_path, class:'nav-link' %>
        </li>
         <li class="nav-item">
          <%= link_to "Books", books_path, class:'nav-link' %>
        </li>
      </ul>
      <ul class="navbar-nav">
         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            User
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

ruby_luongvanchuong/Project_Ruby/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'layouts/header' %>  
    <div class="container">
      <%= yield %>
    </div>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</html>

ruby_luongvanchuong/Project_Ruby/app/views/pages/about.html.erb
<h1>Pages#about</h1>
<h2>This pages About</h2>
<a href="/">Home</a>
<%link_to "Home", about_path %>

ruby_luongvanchuong/Project_Ruby/app/views/pages/home.html.erb
<div class="container">
      <h1>My personnal Home Page</h1>
      <p>You can red more about me, or checkout my blog.</p>
      <a href="/about">About</a>
      <%link_to "About Me, Myself, And I", about_path %>
</div>